version: '3.8'

services:
  db-test:
    image: postgres:16.6
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  crypto-bot:
    image: na3810/bot_cryptoanalyst:test
    container_name: crypto-bot
    restart: always
    volumes:
      - .:/app
      - ./data:/app/database
    env_file:
      - ./.env
    depends_on:
      - db-test
      - redis

volumes:
  postgres_data:
