version: '3.8'

services:
  db-analyst-test:
    image: postgres:16.6
    container_name: analyst_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - analyst_postgres_data:/var/lib/postgresql/data
    ports:
      - "5455:5432"

  redis:
    image: redis:latest
    container_name: redis_crypto_analyst
    restart: always
    ports:
      - "6330:6379"

  crypto-bot:
    image: na3810/bot_cryptoanalyst:test
    container_name: crypto_analyst_bot
    restart: always
    volumes:
      - .:/app
      - ./data:/app/database
    env_file:
      - ./.env
    depends_on:
      - db-analyst-test
      - redis

volumes:
  analyst_postgres_data:
