version: '3.8'

services:
  db-analyst-test:
    image: postgres:16.6
    container_name: crypto_analyst_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - analyst_postgres_data:/var/lib/postgresql/data
    ports:
      - "5455:5432"

  redis-analyst-test:
    image: redis:latest
    container_name: crypto_analyst_redis
    restart: always
    ports:
      - "6330:6379"

  cryptoanalyst_test:
    image: na3810/bot_cryptoanalyst:test
    container_name: crypto_analyst_ai_bot
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db-analyst-test
      - redis-analyst-test

volumes:
  analyst_postgres_data:
