version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  crypto-bot:
    build: .
    container_name: crypto-bot
    volumes:
      - .:/app
      - ./data:/app/database
    env_file:
      - bot/.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
