"""таблица ответа агента

Revision ID: 5ff23721cb44
Revises: ee671b773041
Create Date: 2024-11-16 21:59:55.712254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff23721cb44'
down_revision: Union[str, None] = 'ee671b773041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentanswer', sa.Column('language', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agentanswer', 'language')
    # ### end Alembic commands ###
