"""удалено поле для для тира в investing metrics

Revision ID: 94f9a9d65cae
Revises: d6bdca9a4a7c
Create Date: 2024-11-23 23:16:35.866321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f9a9d65cae'
down_revision: Union[str, None] = 'd6bdca9a4a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_category', sa.String(length=100), nullable=True))
    op.drop_column('project', 'project_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_name', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('project', 'project_category')
    # ### end Alembic commands ###
