"""изменен тип telegram_id

Revision ID: 10fe95c1a036
Revises: f7df029ff7e3
Create Date: 2024-12-12 23:57:27.795625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fe95c1a036'
down_revision: Union[str, None] = 'f7df029ff7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_unique_constraint('uq_user_telegram_id', 'user', ['telegram_id'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calculation_user_id_fkey', 'calculation', type_='foreignkey')
    op.create_foreign_key(None, 'calculation', 'user', ['user_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calculation', type_='foreignkey')

    # Затем удаляем уникальное ограничение на telegram_id
    op.drop_constraint('uq_user_telegram_id', 'user', type_='unique')

    # Восстанавливаем старый внешний ключ, ссылаясь на поле id
    op.create_foreign_key('calculation_user_id_fkey', 'calculation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
