"""добавлены unique для project_id метричных моделей

Revision ID: 82c70750726b
Revises: 10fe95c1a036
Create Date: 2024-12-16 14:11:44.505857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c70750726b'
down_revision: Union[str, None] = '10fe95c1a036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'basic_metrics', ['project_id'])
    op.alter_column('calculation', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('calculation', 'project_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'funds_profit', ['project_id'])
    op.create_unique_constraint(None, 'investing_metrics', ['project_id'])
    op.create_unique_constraint(None, 'manipulative_metrics', ['project_id'])
    op.create_unique_constraint(None, 'market_metrics', ['project_id'])
    op.create_unique_constraint(None, 'network_metrics', ['project_id'])
    op.create_unique_constraint(None, 'social_metrics', ['project_id'])
    op.create_unique_constraint(None, 'tokenomics', ['project_id'])
    op.create_unique_constraint(None, 'top_and_bottom', ['project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'top_and_bottom', type_='unique')
    op.drop_constraint(None, 'tokenomics', type_='unique')
    op.drop_constraint(None, 'social_metrics', type_='unique')
    op.drop_constraint(None, 'network_metrics', type_='unique')
    op.drop_constraint(None, 'market_metrics', type_='unique')
    op.drop_constraint(None, 'manipulative_metrics', type_='unique')
    op.drop_constraint(None, 'investing_metrics', type_='unique')
    op.drop_constraint(None, 'funds_profit', type_='unique')
    op.alter_column('calculation', 'project_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('calculation', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'basic_metrics', type_='unique')
    # ### end Alembic commands ###
