"""добавлено поле category

Revision ID: 02b74c5b0e69
Revises: 94f9a9d65cae
Create Date: 2024-11-27 22:58:30.895981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b74c5b0e69'
down_revision: Union[str, None] = '94f9a9d65cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('category', sa.String(length=100), nullable=True))
    op.drop_column('project', 'project_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_category', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('project', 'category')
    # ### end Alembic commands ###
