"""delete project.category add project.tier

Revision ID: 19
Revises: 18
Create Date: 2025-02-24 23:00:43.646246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19'
down_revision: Union[str, None] = '18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'calculation', 'user', ['user_id'], ['telegram_id'])
    op.create_foreign_key(None, 'funds_profit', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'investing_metrics', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'manipulative_metrics', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'market_metrics', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'network_metrics', 'project', ['project_id'], ['id'])
    op.add_column('project', sa.Column('tier', sa.String(length=30), nullable=True))
    op.drop_column('project', 'category')
    op.create_foreign_key(None, 'project_category_association', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'project_category_association', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'social_metrics', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'tokenomics', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'top_and_bottom', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'top_and_bottom', type_='foreignkey')
    op.drop_constraint(None, 'tokenomics', type_='foreignkey')
    op.drop_constraint(None, 'social_metrics', type_='foreignkey')
    op.drop_constraint(None, 'project_category_association', type_='foreignkey')
    op.drop_constraint(None, 'project_category_association', type_='foreignkey')
    op.add_column('project', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('project', 'tier')
    op.drop_constraint(None, 'network_metrics', type_='foreignkey')
    op.drop_constraint(None, 'market_metrics', type_='foreignkey')
    op.drop_constraint(None, 'manipulative_metrics', type_='foreignkey')
    op.drop_constraint(None, 'investing_metrics', type_='foreignkey')
    op.drop_constraint(None, 'funds_profit', type_='foreignkey')
    op.drop_constraint(None, 'calculation', type_='foreignkey')
    # ### end Alembic commands ###
