"""удалены ненужне поля

Revision ID: 22
Revises: 21
Create Date: 2025-03-23 14:57:58.602881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22'
down_revision: Union[str, None] = '21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds_profit', 'x_value')
    op.drop_column('funds_profit', 'average_price')
    op.drop_column('manipulative_metrics', 'fdv_fundraise')
    op.drop_column('network_metrics', 'tvl_fdv')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_metrics', sa.Column('tvl_fdv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('manipulative_metrics', sa.Column('fdv_fundraise', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('funds_profit', sa.Column('average_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('funds_profit', sa.Column('x_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
