"""удалено поле для тира в social metrics

Revision ID: 5d0dc0e1fefa
Revises: f04c4a90bab1
Create Date: 2024-11-22 19:36:50.542982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0dc0e1fefa'
down_revision: Union[str, None] = 'f04c4a90bab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_metrics', 'social_tier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_metrics', sa.Column('social_tier', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
