"""удалено поле для для тира в base metrics

Revision ID: 806897e7e10f
Revises: 5d0dc0e1fefa
Create Date: 2024-11-22 20:25:52.521167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806897e7e10f'
down_revision: Union[str, None] = '5d0dc0e1fefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basic_metrics', 'base_tier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_metrics', sa.Column('base_tier', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
