"""удалено поле для для тира в investing metrics

Revision ID: d6bdca9a4a7c
Revises: 806897e7e10f
Create Date: 2024-11-22 20:28:25.062886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6bdca9a4a7c'
down_revision: Union[str, None] = '806897e7e10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investing_metrics', 'investing_tier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investing_metrics', sa.Column('investing_tier', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
